"""`AGENTS.md` — what the project is, as opposed to how PowerBuilder works.

The bundle carries the detailed PowerBuilder guidance: skills, the
antipattern catalog and the source-format wiki. `AGENTS.md` records the few
project facts and operating rules an agent needs before choosing one of those
skills.

`AGENTS.md` is the cross-tool convention — Codex, Cursor, Copilot, Zed and
Claude Code all read it — so it is the right file for a kit that refuses to
assume a vendor.

**Two rules, and the second one is the whole design.**

1. Write only what was *established*: the version the user stated, the
   workspace files actually on disk, whether there is a text projection,
   whether there is git. Never a deduction dressed as a fact.
2. **Never touch a file that exists.** It is the project's document,
   hand-maintained, and an installer that rewrote it would destroy work on
   every update. When one is already there the block is printed instead, for
   the user to place.

The cost of getting rule 1 wrong is worth stating, because it is not obvious:
an agent trusts this file. A generated `AGENTS.md` that quietly goes stale
does not fail — it misinforms every session from then on, with authority.
Which is exactly why the PowerBuilder version is asked rather than sniffed,
and why the block below says out loud that a migration invalidates it.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from . import pbversion

FILE_NAME = "AGENTS.md"

#: The heading used for the project facts generated by the installer.
SECTION_HEADING = "## PowerBuilder project"


@dataclass(frozen=True)
class WorkspaceFacts:
    """The install-time facts rendered above the stable workflow rules.

    ``pb_version`` is what the user said, or ``None`` when nobody said.
    The rest is read off the disk, so it is checkable rather than believed.
    """

    pb_version: str | None
    workspaces: tuple[str, ...]
    has_projection: bool
    is_git: bool
    is_svn: bool = False
    #: Effective Git treatment of real projection files, when it can be checked.
    source_protection: str | None = None


def survey(
    target: Path,
    *,
    pb_version: str | None,
    is_git: bool,
    is_svn: bool = False,
    source_protection: str | None = None,
) -> WorkspaceFacts:
    """Look at the project, shallowly and cheaply.

    Two levels deep: PowerBuilder workspaces sit at the root or one
    directory down (`src/`), and a recursive walk of a repository holding
    `.pbl` files and a decade of build output is not worth the seconds.
    """
    workspaces = sorted(
        str(p.relative_to(target)).replace("\\", "/")
        for p in (*target.glob("*.pbw"), *target.glob("*/*.pbw"))
    )
    projection = any(target.glob("ws_objects")) or any(target.glob("*/ws_objects"))
    return WorkspaceFacts(
        pb_version=pb_version,
        workspaces=tuple(workspaces),
        has_projection=projection,
        is_git=is_git,
        is_svn=is_svn,
        source_protection=source_protection,
    )


def _lines(facts: WorkspaceFacts) -> list[str]:
    out = [
        SECTION_HEADING,
        "",
        "`pb-ai-code install` created this install-time snapshot. Maintain it",
        "manually. The installer will not update or overwrite this file.",
        "",
    ]
    if facts.pb_version is None:
        out += [
            "- PowerBuilder release: **not stated**",
            "  Ask before opening an ORCA session or searching Appeon documentation.",
            "  Do not infer the release from exported objects.",
        ]
    else:
        release = pbversion.parse(facts.pb_version)
        out += [
            f"- PowerBuilder release: `{release.value}` ({release.label}).",
            f"  Use `{release.orca_version}` for ORCA and `{release.value}` for",
            "  every Appeon documentation query.",
        ]
    out += [
        "  Update this line whenever the project is migrated to another",
        "  PowerBuilder release.",
    ]

    if facts.workspaces:
        label = "Workspace" if len(facts.workspaces) == 1 else "Workspaces"
        out.append(f"- {label}: {', '.join(f'`{w}`' for w in facts.workspaces)}")
    else:
        out.append("- Workspace: **not found** at the root or one level down.")

    if facts.has_projection:
        out.append("- Text projection: `ws_objects/` found at the root or one level down.")
    else:
        out.append("- Text projection: **not found**.")

    if facts.is_git:
        out.append("- Version control: Git.")
    elif facts.is_svn:
        out.append("- Version control: Subversion working copy.")
    else:
        out.append("- Version control: **Git or SVN working copy not found**.")

    if facts.has_projection and facts.source_protection in {"unprotected", "mixed"}:
        qualifier = "inconsistent" if facts.source_protection == "mixed" else "missing"
        out += [
            f"- Git source protection: **{qualifier} for `.sr*` files**. Do not run",
            "  a write workflow until the effective attributes have been reviewed.",
            "  The installer reports this condition but never edits `.gitattributes`.",
        ]
    elif facts.has_projection and facts.source_protection == "nondiffable":
        out += [
            "- Source diffs: **some `.sr*` files are binary to Git**. Their bytes",
            "  are protected, but review those entries through an ORCA body diff.",
        ]
    elif facts.has_projection and facts.is_git and facts.source_protection == "unknown":
        out += [
            "- Git source protection: **unknown** because no real `.sr*` file was",
            "  available to check. Do not infer safety from a synthetic path.",
        ]

    out += [
        "",
        "## Approval before changes",
        "",
        "- Start every request about this project with read-only inspection.",
        "  Report what you found before suggesting changes.",
        "- Do not edit files, import PowerBuilder objects, or run commands that",
        "  change persistent project state until the user approves a plan.",
        "- If a change is warranted, propose a concrete, scoped plan and wait for",
        "  the user's explicit approval. The original request is not approval,",
        "  even when it says to fix, change, or implement something.",
        "- Treat questions about code as analysis only unless the user accepts a",
        "  proposed plan. After approval, ask again before substantially expanding",
        "  its scope.",
        "",
        "## PowerBuilder workflow",
        "",
        "- Use the installed `pb-*` skills for review, impact analysis and",
        "  changes.",
        "- Use the configured `pb_*` ORCA tools for every `.pbl` operation.",
        "- Never edit or delete files under `ws_objects/`; PowerBuilder owns it.",
        "- Never edit or replace a `.pbl` file directly.",
        "- Read the PowerBuilder release before opening an ORCA session; use its",
        "  derived ORCA token stated above."
        "- At the start of a session, run `pb-ai-code update --check --json` once.",
        "  If it reports `update_available: true`, tell the user and offer to run",
        "  `pb-ai-code update`; never update the machine or this project without",
        "  the user's approval.",
    ]
    return out


def block(facts: WorkspaceFacts) -> str:
    """The section, as text, with a trailing newline."""
    return "\n".join(_lines(facts)) + "\n"


def read_version(target: Path) -> str | None:
    """The version an earlier install (or a person) wrote, if any.

    Used as the default when asking again, so a re-install is a keypress
    rather than an interrogation. Deliberately forgiving about the
    surrounding text: this is a file people edit.
    """
    path = target / FILE_NAME
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    match = re.search(r"PowerBuilder release:\s*`?(pb\d{4}(?:r\d+)?)`?", text, re.I)
    return match.group(1).lower() if match else None


def create(target: Path, facts: WorkspaceFacts) -> bool:
    """Write `AGENTS.md` when there is none. ``False`` when one exists.

    The check is the whole safety property, so it is one line and it is here
    rather than at the call site: an existing file is never opened, never
    appended to, never backed up and rewritten.
    """
    path = target / FILE_NAME
    if path.exists():
        return False
    header = [
        f"# {target.name}",
        "",
        "Instructions for AI coding agents working on this project.",
        "",
    ]
    path.write_text("\n".join(header) + "\n" + block(facts), encoding="utf-8", newline="\r\n")
    return True
